module.exports = [
  {
    slug: 'id-form',
    title: 'ID form',
    formService: 'tally',
    formId: 'w4QGAA',
    category: 'General',
  },
  {
    slug: 'limited-company-accounts',
    title: 'Limited company accounts',
    formService: 'tally',
    formId: 'meBvrq',
    category: 'Limited company',
  },
  {
    slug: 'limited-company-new-client',
    title: 'New client information',
    formService: 'tally',
    formId: 'mVGoLN',
    parameters: 'limited_company=yes',
    category: 'Limited company',
  },
  {
    slug: 'limited-company-new-client-payroll',
    title: 'New client information with payroll',
    formService: 'tally',
    formId: 'mVGoLN',
    parameters: 'limited_company=yes&payroll=yes',
    category: 'Limited company',
  },
  {
    slug: 'limited-company-new-client-vat',
    title: 'New client information with VAT',
    formService: 'tally',
    formId: 'mVGoLN',
    parameters: 'limited_company=yes&vat=yes',
    category: 'Limited company',
  },
  {
    slug: 'limited-company-new-client-vat-payroll',
    title: 'New client information with VAT and payroll',
    formService: 'tally',
    formId: 'mVGoLN',
    parameters: 'limited_company=yes&payroll=yes&vat=yes',
    category: 'Limited company',
  },
  {
    slug: 'self-assessment-new-client',
    title: 'New client information',
    formService: 'tally',
    formId: 'mVGoLN',
    parameters: 'self_assessment=yes',
    category: 'Self Assessment',
  },
  {
    slug: 'self-assessment-questionnaire-2023-24',
    title: 'Self Assessment Tax Return 2023/24',
    formService: 'tally',
    formId: 'w2e90g',
    category: 'Self Assessment',
  },
  {
    slug: 'self-assessment-questionnaire',
    title: 'Self Assessment Tax Return 2024/25',
    formService: 'tally',
    formId: 'wQ4Pa1',
    category: 'Self Assessment',
  },
  {
    slug: 'sole-trader-working-from-home-expenses-calculator',
    title: 'Sole Trader Working From Home Expenses Calculator',
    formService: 'tally',
    formId: 'npLXLy',
    category: 'General',
  },
]
