module.exports = [
  {
    slug: 'id-form',
    title: 'ID form',
    formService: 'airtable',
    formId: 'shrMae0GzMBFvd3gX',
    category: 'General',
  },
  {
    slug: 'incorporating-limited-company',
    title: 'Incorporating a limited company',
    formService: 'airtable',
    formId: 'shrkHFUHUTDro4ZXS',
    category: 'Limited company',
  },
  {
    slug: 'limited-company-new-client',
    title: 'New client information',
    formService: 'airtable',
    formId: 'shrs1dcUgea35djWU',
    category: 'Limited company',
  },
  {
    slug: 'limited-company-new-client-payroll',
    title: 'New client information with payroll',
    formService: 'airtable',
    formId: 'shrkljFv66yKwOK0y',
    category: 'Limited company',
  },
  {
    slug: 'limited-company-new-client-vat',
    title: 'New client information with VAT',
    formService: 'airtable',
    formId: 'shr7PcSQITiOsHE70',
    category: 'Limited company',
  },
  {
    slug: 'limited-company-new-client-vat-payroll',
    title: 'New client information with VAT and payroll',
    formService: 'airtable',
    formId: 'shrStgwWagdG5RG7x',
    category: 'Limited company',
  },
  {
    slug: 'payroll-agent',
    title: 'Payroll agent authorisation',
    formService: 'airtable',
    formId: 'shrS4wBW0DUH2O1fw',
    category: 'Payroll',
  },
  {
    slug: 'register-as-employer',
    title: 'Register as an employer',
    formService: 'airtable',
    formId: 'shrNT6py9gPGfxxwk',
    category: 'Payroll',
  },
  {
    slug: 'register-for-vat',
    title: 'Register for VAT',
    formService: 'airtable',
    formId: 'shrWVzEPHH148pLP4',
    category: 'VAT',
  },
  {
    slug: 'self-assessment-questionnaire',
    title: 'Self Assessment Tax Return 2021-22',
    formService: 'airtable',
    formId: 'shrBkxympvuEuBHEB',
    category: 'Self Assessment',
  },
  {
    slug: 'sole-trader-new-client',
    title: 'New client information',
    formService: 'airtable',
    formId: 'shrcr4sK2DGkXAFr2',
    category: 'Sole trader',
  },
  {
    slug: 'sole-trader-new-client-payroll',
    title: 'New client information with payroll',
    formService: 'airtable',
    formId: 'shr2vEvFOnvwzetjg',
    category: 'Sole trader',
  },
  {
    slug: 'sole-trader-new-client-vat',
    title: 'New client information with VAT',
    formService: 'airtable',
    formId: 'shrRUEGw8Xavp0gkk',
    category: 'Sole trader',
  },
  {
    slug: 'sole-trader-new-client-vat-payroll',
    title: 'New client information with VAT and payroll',
    formService: 'airtable',
    formId: 'shrcS86noMfFICBvj',
    category: 'Sole trader',
  },
  {
    slug: 'vat-agent',
    title: 'VAT agent authorisation',
    formService: 'airtable',
    formId: 'shrbaJctHVo6QUjQm',
    category: 'VAT',
  },
]
