[dev]
  framework = "eleventy"
  port = 8888
  command = "npx @11ty/eleventy --serve --incremental"

[build]
  base = "web/"
  command = "npm run netlify:build"
  publish = "dist/"
  # Only build if changes are in the web directory
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "22.17.1"
  NPM_FLAGS = "--prefix=/dev/null"

[functions]
  directory = "src/functions"
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
