[dev]
  framework = "eleventy"
  port = 8888
  command = "npx @11ty/eleventy --serve --incremental"

[build]
  base = "web/"
  command = "npm run build"
  publish = "dist/"
  # Only build if changes are in the web directory
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[functions]
  directory = "src/functions"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
